import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — VoidView",
  description: "Privacy Policy for VoidView (voidview.space).",
};

export default function PrivacyPage() {
  // Keep static (no Date.now) to avoid any SSR/client mismatch issues
  const lastUpdated = "October 26, 2023";

  const h2 = "text-lg font-semibold text-zinc-900 mt-8";
  const h3 = "text-base font-semibold text-zinc-900 mt-5";
  const p = "text-zinc-700 leading-relaxed";
  const li = "text-zinc-700 leading-relaxed";

  return (
    <main className="space-y-6">
      <header className="space-y-2">
        <h1 className="text-3xl font-semibold text-zinc-900">Privacy Policy</h1>
        <p className="text-sm text-zinc-600">Last Updated: {lastUpdated}</p>
      </header>

      <section className="rounded-3xl bg-white border border-black/5 p-6 md:p-8">
        <p className={p}>
          This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your
          information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>

        <p className={p + " mt-4"}>
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
          and use of information in accordance with this Privacy Policy.
        </p>

        <h2 className={h2}>1. Interpretation and Definitions</h2>

        <h3 className={h3}>Interpretation</h3>
        <p className={p}>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The
          following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className={h3}>Definitions</h3>
        <p className={p}>For the purposes of this Privacy Policy:</p>

        <ul className="mt-3 space-y-2">
          <li className={li}>
            <span className="font-medium">Account</span> means a unique account created for You to access our Service or
            parts of our Service.
          </li>
          <li className={li}>
            <span className="font-medium">Company</span> (referred to as either &quot;the Company&quot;, &quot;We&quot;,
            &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to VoidView (operated by an Individual located in
            Switzerland).
          </li>
          <li className={li}>
            <span className="font-medium">Country</span> refers to: Switzerland.
          </li>
          <li className={li}>
            <span className="font-medium">Cookies</span> are small files that are placed on Your computer, mobile device,
            or any other device by a website, containing the details of Your browsing history on that website among its
            many uses.
          </li>
          <li className={li}>
            <span className="font-medium">Device</span> means any device that can access the Service such as a computer,
            a cellphone, or a digital tablet.
          </li>
          <li className={li}>
            <span className="font-medium">Personal Data</span> is any information that relates to an identified or
            identifiable individual.
          </li>
          <li className={li}>
            <span className="font-medium">Service</span> refers to the Website.
          </li>
          <li className={li}>
            <span className="font-medium">Service Provider</span> means any natural or legal person who processes the data
            on behalf of the Company. It refers to third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the
            Service, or to assist the Company in analyzing how the Service is used.
          </li>
          <li className={li}>
            <span className="font-medium">Usage Data</span> refers to data collected automatically, either generated by
            the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </li>
          <li className={li}>
            <span className="font-medium">Website</span> refers to VoidView, accessible from{" "}
            <a className="underline hover:text-zinc-900" href="https://voidview.space" target="_blank" rel="noreferrer">
              https://voidview.space
            </a>
          </li>
          <li className={li}>
            <span className="font-medium">You</span> means the individual accessing or using the Service, or the company,
            or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className={h2}>2. Collecting and Using Your Personal Data</h2>

        <h3 className={h3}>Types of Data Collected</h3>

        <h3 className={h3}>Usage Data</h3>
        <p className={p}>Usage Data is collected automatically when using the Service.</p>

        <p className={p + " mt-4"}>
          Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address),
          browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the
          time spent on those pages, unique device identifiers and other diagnostic data.
        </p>

        <p className={p + " mt-4"}>
          When You access the Service by or through a mobile device, We may collect certain information automatically,
          including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address
          of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device
          identifiers and other diagnostic data.
        </p>

        <h3 className={h3}>Tracking Technologies and Cookies</h3>
        <p className={p}>
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
          information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to
          improve and analyze Our Service.
        </p>

        <p className={p + " mt-4"}>
          You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You
          do not accept Cookies, You may not be able to use some parts of our Service.
        </p>

        <h3 className={h3}>Use of Your Personal Data</h3>
        <p className={p}>The Company may use Personal Data for the following purposes:</p>
        <ul className="mt-3 list-disc pl-5 space-y-2">
          <li className={li}>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li className={li}>To manage Your requests: To attend and manage Your requests to Us.</li>
          <li className={li}>
            For business transfers: We may use Your information to evaluate or conduct a merger, divestiture,
            restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.
          </li>
          <li className={li}>
            For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage
            trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service,
            products, services, marketing, and your experience.
          </li>
        </ul>

        <h3 className={h3}>Sharing Your Personal Data</h3>
        <p className={p}>We may share Your personal information in the following situations:</p>
        <ul className="mt-3 list-disc pl-5 space-y-2">
          <li className={li}>
            With Service Providers: We may share Your personal information with Service Providers to monitor and analyze
            the use of our Service, to show advertisements to You, to support and maintain our Service, and for
            remarketing purposes.
          </li>
          <li className={li}>
            With Affiliates: We may share Your information with Our affiliates, in which case we will require those
            affiliates to honor this Privacy Policy.
          </li>
          <li className={li}>
            With Business Partners: We may share Your information with Our business partners to offer You certain
            products, services, or promotions.
          </li>
          <li className={li}>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
        </ul>

        <h2 className={h2}>3. Analytics, Ads, and Remarketing</h2>
        <p className={p}>
          We use third-party Service Providers to monitor and analyze the use of our Service, show advertisements, and
          perform remarketing services.
        </p>

        <h3 className={h3}>Google Analytics</h3>
        <p className={p}>
          Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google
          uses the data collected to track and monitor the use of our Service. This data is shared with other Google
          services. Google may use the collected data to contextualize and personalize the ads of its own advertising
          network.
        </p>

        <p className={p + " mt-4"}>
          You can opt-out of having made your activity on the Service available to Google Analytics by installing the
          Google Analytics opt-out browser add-on.
        </p>

        <p className={p + " mt-4"}>
          For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page:{" "}
          <a className="underline hover:text-zinc-900" href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">
            https://policies.google.com/privacy
          </a>
        </p>

        <h3 className={h3}>Advertising</h3>
        <p className={p}>
          We use Service Providers to show advertisements to You to help support and maintain Our Service.
        </p>

        <p className={p + " mt-4"}>
          Google AdSense &amp; DoubleClick Cookie: Google, as a third-party vendor, uses cookies to serve ads on our
          Service. Google&apos;s use of the DoubleClick cookie enables it and its partners to serve ads to our users based
          on their visit to our Service or other websites on the Internet. You may opt out of the use of the DoubleClick
          Cookie for interest-based advertising by visiting the Google Ads Settings web page.
        </p>

        <h3 className={h3}>Behavioral Remarketing</h3>
        <p className={p}>
          The Company uses remarketing services to advertise on third-party websites to You after You visited our Service.
          We and our third-party vendors use cookies to inform, optimize and serve ads based on Your past visits to our
          Service.
        </p>

        <p className={p + " mt-4"}>
          Google Ads (AdWords): Google Ads remarketing service is provided by Google Inc. You can opt-out of Google
          Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads
          Settings page:{" "}
          <a className="underline hover:text-zinc-900" href="http://www.google.com/settings/ads" target="_blank" rel="noreferrer">
            http://www.google.com/settings/ads
          </a>
        </p>

        <h2 className={h2}>4. GDPR (General Data Protection Regulation) &amp; Swiss FADP Privacy Policy</h2>
        <p className={p}>
          If You are from the European Economic Area (EEA), the UK, or Switzerland, the legal basis for collecting and
          using the personal information described in this Privacy Policy depends on the Personal Data we collect and the
          specific context in which we collect it.
        </p>

        <h3 className={h3}>Legal Basis for Processing</h3>
        <ul className="mt-3 list-disc pl-5 space-y-2">
          <li className={li}>Legitimate Interests: We process Your data to provide the Service, analyze usage statistics, and ensure security.</li>
          <li className={li}>Consent: We rely on Your consent for tracking cookies and advertising purposes.</li>
        </ul>

        <h3 className={h3}>Your Rights under GDPR and Swiss FADP</h3>
        <p className={p}>
          The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise
          Your rights. You have the right under this Privacy Policy, and by law if You are within the EU or Switzerland,
          to:
        </p>

        <ul className="mt-3 list-disc pl-5 space-y-2">
          <li className={li}>Request access to Your Personal Data.</li>
          <li className={li}>Request correction of the Personal Data that We hold about You.</li>
          <li className={li}>Object to processing of Your Personal Data.</li>
          <li className={li}>Request erasure of Your Personal Data.</li>
          <li className={li}>Request the transfer of Your Personal Data.</li>
          <li className={li}>Withdraw Your consent.</li>
        </ul>

        <p className={p + " mt-4"}>
          You may exercise Your rights of access, rectification, cancellation, and opposition by contacting Us. Please
          note that we may ask You to verify Your identity before responding to such requests.
        </p>

        <h2 className={h2}>5. CalOPPA (California Online Privacy Protection Act)</h2>

        <h3 className={h3}>&quot;Do Not Track&quot; Policy as Required by CalOPPA</h3>
        <p className={p}>
          Our Service does not respond to Do Not Track signals. However, some third-party websites may keep track of Your
          browsing activities. If You are visiting such websites, You can set Your preferences in Your web browser to
          inform websites that You do not want to be tracked. You can enable or disable DNT by visiting the preferences
          or settings page of Your web browser.
        </p>

        <h2 className={h2}>6. CCPA and CPRA Privacy Notice (California)</h2>
        <p className={p}>This section provides additional details for residents of California.</p>

        <h3 className={h3}>Categories of Personal Information Collected</h3>
        <p className={p}>
          We collect information that identifies, relates to, describes, references, is capable of being associated
          with, or could reasonably be linked, directly or indirectly, with a particular consumer or device. The
          following is a list of categories of personal information which we may collect or may have been collected from
          California residents within the last twelve (12) months:
        </p>

        <ul className="mt-3 list-disc pl-5 space-y-2">
          <li className={li}>Category A: Identifiers. (e.g., Internet Protocol address, online identifier, unique device identifier).</li>
          <li className={li}>Category F: Internet or other similar network activity. (e.g., interaction with our Website and advertisements).</li>
        </ul>

        <h3 className={h3}>Your Rights under the CCPA/CPRA</h3>
        <p className={p}>The CCPA provides California residents with specific rights regarding their personal information:</p>

        <ul className="mt-3 list-disc pl-5 space-y-2">
          <li className={li}>
            The Right to Know: You have the right to request that we disclose certain information to You about our
            collection and use of Your personal information over the past 12 months.
          </li>
          <li className={li}>
            The Right to Delete: You have the right to request that we delete any of Your personal information that we
            collected from You and retained, subject to certain exceptions.
          </li>
          <li className={li}>The Right to Correct: You have the right to request correction of inaccurate personal information.</li>
          <li className={li}>
            The Right to Opt-Out of Sale or Sharing: We do not sell personal information for monetary value. However, the
            use of advertising and analytics cookies may be considered a &quot;sale&quot; or &quot;sharing&quot; of
            personal information under California law. You have the right to opt-out of the sale or sharing of Your
            personal information.
          </li>
        </ul>

        <p className={p + " mt-4"}>To exercise Your rights: Please contact us at support@voidview.space.</p>

        <h2 className={h2}>7. Children&apos;s Privacy</h2>
        <p className={p}>
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
          information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child
          has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data
          from anyone under the age of 13 without verification of parental consent, We take steps to remove that
          information from Our servers.
        </p>

        <h2 className={h2}>8. Retention of Your Personal Data</h2>
        <p className={p}>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
          Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to comply with applicable laws), resolve
          disputes, and enforce our legal agreements and policies.
        </p>

        <h2 className={h2}>9. Transfer of Your Personal Data</h2>
        <p className={p}>
          Your information, including Personal Data, is processed at the Company&apos;s operating offices in Switzerland
          and in any other places where the parties involved in the processing are located. It means that this
          information may be transferred to — and maintained on — computers located outside of Your state, province,
          country, or other governmental jurisdiction where the data protection laws may differ than those from Your
          jurisdiction.
        </p>

        <p className={p + " mt-4"}>
          Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement
          to that transfer.
        </p>

        <h2 className={h2}>10. Links to Other Websites</h2>
        <p className={p}>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third-party
          link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy
          of every site You visit.
        </p>

        <p className={p + " mt-4"}>
          We have no control over and assume no responsibility for the content, privacy policies, or practices of any
          third-party sites or services.
        </p>

        <h2 className={h2}>11. Changes to this Privacy Policy</h2>
        <p className={p}>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
          Privacy Policy on this page.
        </p>

        <p className={p + " mt-4"}>
          We will let You know via a prominent notice on Our Service, prior to the change becoming effective and update
          the &quot;Last updated&quot; date at the top of this Privacy Policy.
        </p>

        <h2 className={h2}>12. Contact Us</h2>
        <p className={p}>If you have any questions about this Privacy Policy, You can contact us:</p>

        <ul className="mt-3 list-disc pl-5 space-y-2">
          <li className={li}>
            By email:{" "}
            <a className="underline hover:text-zinc-900" href="mailto:support@voidview.space">
              support@voidview.space
            </a>
          </li>
        </ul>
      </section>
    </main>
  );
}